In [9]:
#import os
#os.environ['PATH'].split(';')

In [10]:
import numpy as np
from numpy import array

In [11]:
# further reading at https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html

x = array([0, 0, 0]) #(3,)
y = array([[1], [1], [1], [1]]) #(4,1)
z = array([[1,1], [1,1], [1,1], [1,1]]) #(4,2)

a = x + y
print("shape:", a.shape)
print("a: ", a)

b = y + z
print("shape:", b.shape)
print ("b: ", b)

# for c, x is not broadcastable like z.
# The shape of (x + y) is (4, 3), and the shape of z is (4, 2). Hence 3 not equal to 2, so matrix multiplication is not possible.

#c = z + x
#print ("c: ", c)


shape: (4, 3)
a:  [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
shape: (4, 2)
b:  [[2 2]
 [2 2]
 [2 2]
 [2 2]]


In [12]:
#d = np.matmul((x+y), z)
#print ("d: ", d)

In [1]:
result = np.log(4)
print(result)

NameError: name 'np' is not defined