In [2]:
#import os
#os.environ['PATH'].split(';')

In [1]:
import numpy as np
from numpy import array

In [4]:
# further reading at https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html

x = array([0, 0, 0]) #(3,)
y = array([[1], [1], [1], [1]]) #(4,1)
z = array([[1,1], [1,1], [1,1], [1,1]]) #(4,2)

a = x + y
print("shape:", a.shape)
print("a: ", a)

b = y + z
print("shape:", b.shape)
print ("b: ", b)

# for c, x is not broadcastable like z.
# The shape of (x + y) is (4, 3), and the shape of z is (4, 2). Hence 3 not equal to 2, so matrix multiplication is not possible.

c = z + x
print ("c: ", c)


shape: (4, 3)
a:  [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
shape: (4, 2)
b:  [[2 2]
 [2 2]
 [2 2]
 [2 2]]


ValueError: operands could not be broadcast together with shapes (4,2) (3,) 

In [9]:
d = np.matmul((x+y), z)
print ("d: ", d)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)